--PLSQL BUSCAR COM FUNCTION

CREATE OR REPLACE FUNCTION BUSCANOME(VNOME IN VARCHAR2)
RETURN SYS_REFCURSOR
AS 
VLINHA SYS_REFCURSOR;
BEGIN
	OPEN VLINHA FOR SELECT * FROM VENDAS WHERE UPPER(VENDEDOR)=UPPER(VNOME);
	RETURN VLINHA;
END;
/

-- testando:
SELECT BUSCANOME('SAMUEL') FROM DUAL;
